# REUSE.toml
#
# This file keeps track of licensing within all files in the repository except src/**.
# For licensing information in the source code, refer to the headers and comments in each file.
# Each file in the source code includes copyright authors and SPDX license identifiers.

version = 1

# README, documentaiton content, and branding
[[annotations]]
path = [

    "README.md",
    "docs/content/**",
    "misc/old-docs/**",
    "assets/images/internal/branding/**",
]
SPDX-FileCopyrightText = [
"2025-2026 Illinois_Roadbuff (Rogue Jr) <illinois_roadbuff@proton.me>",
"2025-2026 Project Roadwork and Contributors"]

SPDX-License-Identifier = "CC-BY-SA-4.0"

# Documentation website
[[annotations]]
path = [
  "docs/app.config.ts",
  "docs/nuxt.config.ts",
  "docs/.npmrc",
  "docs/package.json",
  "docs/pnpm-lock.yaml",
  "docs/README.md",
  "docs/tailwind.config.js",
  "docs/tsconfig.json",
  "docs/assets/css/**"
]
SPDX-FileCopyrightText = [
  "2025-2026 Illinois_Roadbuff (Rogue Jr) <illinois_roadbuff@proton.me>",
  "2025-2026 Project Roadwork and Contributors",
  "2024 Tony Zhang"
]
SPDX-License-Identifier = "MIT"
SPDX-FileComment = "Uses the shadcn-docs-nuxt template"

# Benchmark Graphs
[[annotations]]
path = [
    "assets/images/internal/benchmarks/scriptbench**",
]
SPDX-FileCopyrightText = ["2026 Illinois_Roadbuff (Rogue Jr) <illinois_roadbuff@proton.me>"]
SPDX-License-Identifier = "CC-BY-4.0"
SPDX-FileComment = """
Generated using Scriptbench by AsynchronousAI, which is under the MIT license. \
Originally going to be generated by Benchmarker by boatbomber; however, it is a paid plugin and there is no known license to it.
"""

# Other MPL-licensed files
[[annotations]]
path = [
    "NOTICE",
    "test.project.json",
    "standalone.project.json",
    "package.json",
    "typescript.project.json",
    ".forgejo/workflows/**"
]
SPDX-FileCopyrightText = [
"2025-2026 Illinois_Roadbuff (Rogue Jr) <illinois_roadbuff@proton.me>",
"2025-2026 Project Roadwork and Contributors"]

SPDX-License-Identifier = "MPL-2.0"

# Illinois_Roadbuff's images and work under CC BY-SA 4.0
[[annotations]]
path = [

    "assets/images/external/crossroads/**",
    "assets/images/external/noncommons/**",
    "assets/images/internal/figures/**",

]
SPDX-FileCopyrightText = [
"2025-2026 Illinois_Roadbuff (Rogue Jr) <illinois_roadbuff@proton.me>",
]
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = [
    "assets/images/external/commons/View_of_Weber_Road_and_Division_Street_in_Crest_Hill,_Illinois_January_2026_11.jpg"
]
SPDX-FileCopyrightText = [
"2025-2026 Illinois_Roadbuff (Rogue Jr) <illinois_roadbuff@proton.me>",
]
SPDX-License-Identifier = "CC-BY-SA-4.0"
SPDX-FileComment = "Source: https://commons.wikimedia.org/wiki/File:View_of_Weber_Road_and_Division_Street_in_Crest_Hill,_Illinois_(January_2026)_11.tif"

# Illinois_Roadbuff's images and work under CC BY 4.0
[[annotations]]
path = [

    "assets/images/external/commons/New_Traffic_Signals_in_Lockport,_Illinois_November_2025_02.jpg",
    "assets/images/external/commons/i55_i355_interchange.jpg"

]
SPDX-FileCopyrightText = [
"2025-2026 Illinois_Roadbuff (Rogue Jr) <illinois_roadbuff@proton.me>",
]

SPDX-License-Identifier = "CC-BY-4.0"

# Common Property
[[annotations]]
path = [
    ".gitignore",
    "CODE_OF_CONDUCT.md",
    "CONTRIBUTING.md",
    "SECURITY.md",
    ".forgejo/ISSUE_TEMPLATE/bug_report.md",
    ".forgejo/ISSUE_TEMPLATE/feature_request.md",
    ".forgejo/PULL_REQUEST_TEMPLATE.md",
    ".github/ISSUE_TEMPLATE/notice.md",
    ".github/pull_request_template.md",
    "pesde.toml",
    "pesde.lock",
    "wally.lock",
    "wally.toml",
    ".luaurc",
    ".gitattributes",
    ".zed/settings.json",
    ".json",
    "tsconfig.json",
    "pnpm-lock.yaml",
    "docs/.vscode/**",
    "docs/.gitignore"

]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0 OR Unlicense"
