name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: codeberg-small

    steps:
      - uses: actions/checkout@v5

      - name: Check commit message
        run: |
          MESSAGE=$(git log -1 --pretty=%B)
          echo "Commit message: $MESSAGE"

          echo "$MESSAGE" | grep -q "^docs:" || {
            echo "Skipping publish: no docs: prefix"
            exit 0
          }

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: docs/pnpm-lock.yaml

      - name: Generate site
        run: |
          cd docs
          pnpm install --frozen-lockfile --prefer-offline
          pnpm generate

      - uses: actions/git-pages@v2
        with:
          site: https://project-roadwork.codeberg.page/light-reflector/
          token: ${{ forge.token }}
          source: docs/.output/public/
