-- USAGE: lightreflector/shared/version.luau
-- Version for Light Reflector

--[[

   This Source Code Form is subject to the terms of the Mozilla Public
   License, v. 2.0. If a copy of the MPL was not distributed with this
   file, You can obtain one at https://mozilla.org/MPL/2.0/.

]]

local version = table.freeze({ major = 1, minor = 0, patch = 0, pre_release = "alpha", build = 2 })

return "1.0.0-alpha.2"
